repository: fernandosg/jekyll-terremoto-cdmx.github.io

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink : /:year
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Terremoto CDMX - Equipo Humanitario de Codeando México"
keywords:    "terremoto, cdmx, mexico, tecnologia"
description: "Tecnología de respuesta rápida ante el terremoto de CDMX"
source_link: "https://odd17.codeandomexico.org"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-icon.png"
google_analytics_key: "UA-92890640-1"

gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
### template colors, used site-wide via css ###
colors:
  black:     '#333333'
  white:     '#ffffff'
  gray:      '#fafafa'
  blue:      '#f3476d'
  yellow:    '#f7c824'
  intro:     '#3B82C1'
  phones:    '#ed7950'
  map:       '#578e77'

kramdown:
  auto_ids:  false
